-- MySQL Script generated by MySQL Workbench
-- Mon Dec 27 15:24:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema QLBanSach
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema QLBanSach
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `QLBanSach` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `QLBanSach` ;

-- -----------------------------------------------------
-- Table `QLBanSach`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QLBanSach`.`author` (
  `author_code` INT NOT NULL AUTO_INCREMENT,
  `author_name` VARCHAR(255) NULL DEFAULT NULL,
  `author_address` VARCHAR(255) NULL DEFAULT NULL,
  `author_biography` VARCHAR(500) NULL DEFAULT NULL,
  `author_phone_number` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`author_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `QLBanSach`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QLBanSach`.`customer` (
  `customer_code` INT NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(255) NOT NULL,
  `account_id` VARCHAR(100) NULL DEFAULT NULL,
  `account_password` VARCHAR(100) NULL DEFAULT NULL,
  `customer_email` VARCHAR(100) NOT NULL,
  `customer_address` VARCHAR(255) NULL DEFAULT NULL,
  `customer_phone_number` VARCHAR(36) NULL DEFAULT NULL,
  `customer_gender` CHAR(1) NULL DEFAULT NULL,
  `customer_birth_day` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`customer_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `QLBanSach`.`bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QLBanSach`.`bill` (
  `bill_code` INT NOT NULL AUTO_INCREMENT,
  `paid` BIT(1) NULL DEFAULT NULL,
  `delivery_day` DATETIME NULL DEFAULT NULL,
  `booking_day` DATETIME NULL DEFAULT NULL,
  `delivery_status` BIT(1) NULL DEFAULT NULL,
  `customer_code` INT NULL DEFAULT NULL,
  PRIMARY KEY (`bill_code`),
  INDEX `fk_bill_customer` (`customer_code` ASC) VISIBLE,
  CONSTRAINT `fk_bill_customer`
    FOREIGN KEY (`customer_code`)
    REFERENCES `QLBanSach`.`customer` (`customer_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `QLBanSach`.`publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QLBanSach`.`publisher` (
  `publisher_code` INT NOT NULL AUTO_INCREMENT,
  `publisher_name` VARCHAR(255) NULL DEFAULT NULL,
  `publisher_address` VARCHAR(255) NULL DEFAULT NULL,
  `publisher_phone_number` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`publisher_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `QLBanSach`.`topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QLBanSach`.`topic` (
  `topic_code` INT NOT NULL AUTO_INCREMENT,
  `topic_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`topic_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `QLBanSach`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QLBanSach`.`book` (
  `book_code` INT NOT NULL AUTO_INCREMENT,
  `book_name` VARCHAR(255) NULL DEFAULT NULL,
  `book_price` FLOAT NOT NULL,
  `book_description` VARCHAR(500) NULL DEFAULT NULL,
  `description_image_urls` VARCHAR(500) NULL DEFAULT NULL,
  `book_update_day` DATETIME NULL DEFAULT NULL,
  `book_stock` INT NULL DEFAULT NULL,
  `topic_code` INT NULL DEFAULT NULL,
  `publisher_code` INT NULL DEFAULT NULL,
  PRIMARY KEY (`book_code`),
  INDEX `fk_book_topic` (`topic_code` ASC) VISIBLE,
  INDEX `fk_book_publisher` (`publisher_code` ASC) VISIBLE,
  CONSTRAINT `fk_book_publisher`
    FOREIGN KEY (`publisher_code`)
    REFERENCES `QLBanSach`.`publisher` (`publisher_code`),
  CONSTRAINT `fk_book_topic`
    FOREIGN KEY (`topic_code`)
    REFERENCES `QLBanSach`.`topic` (`topic_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `QLBanSach`.`bill_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QLBanSach`.`bill_detail` (
  `bill_code` INT NOT NULL,
  `book_code` INT NOT NULL,
  `amount` INT NULL DEFAULT NULL,
  `unit_price` FLOAT NOT NULL,
  PRIMARY KEY (`bill_code`, `book_code`),
  INDEX `fk_bill_detail_book` (`book_code` ASC) VISIBLE,
  CONSTRAINT `fk_bill_detail_bill`
    FOREIGN KEY (`bill_code`)
    REFERENCES `QLBanSach`.`bill` (`bill_code`),
  CONSTRAINT `fk_bill_detail_book`
    FOREIGN KEY (`book_code`)
    REFERENCES `QLBanSach`.`book` (`book_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `QLBanSach`.`book_author_relationship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QLBanSach`.`book_author_relationship` (
  `book_code` INT NOT NULL,
  `author_code` INT NOT NULL,
  `author_role` VARCHAR(255) NULL DEFAULT NULL,
  `author_position` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`book_code`, `author_code`),
  INDEX `fk_book_author_relationship_author` (`author_code` ASC) VISIBLE,
  CONSTRAINT `fk_book_author_relationship_author`
    FOREIGN KEY (`author_code`)
    REFERENCES `QLBanSach`.`author` (`author_code`),
  CONSTRAINT `fk_book_author_relationship_book`
    FOREIGN KEY (`book_code`)
    REFERENCES `QLBanSach`.`book` (`book_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
